spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examen_microservicios_2024 #jdbc:mysql://jirasyncdb.cfppua5tmn1g.us-west-2.rds.amazonaws.com:3306/escuela_java_2024 #jdbc:mysql://localhost:3306/database2024
    username: root #usuario #root
    password: changeme #password

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/